#!/bin/sh
# https://git.christoph-polcin.com/keyring/
# Simplified BSD License

set -e

[ -z "$SSH_AUTH_SOCK" ] && echo export SSH_AUTH_SOCK && exit 1
[ -z "$PASS_KEY_PREFIX" ] && PASS_KEY_PREFIX='keyring'

SSH_ASKPASS="$0"
export SSH_ASKPASS

if [ ! -S "$SSH_AUTH_SOCK" ]
then
    ssh-agent -a "$SSH_AUTH_SOCK" >/dev/null 2>&1 && sleep 1
fi

[ $# -eq 0 ] && exit 0

if [ "$1" = '--eval' ] || [ "$1" = '-e' ]; then
    shift
    echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK; export SSH_AUTH_SOCK;";
fi

if [ "$1" = '--add' ] || [ "$1" = '-a' ]; then
    if [ $# -gt 1 ]; then
        shift
        echo "keyring +" >&2
        ssh-add $@ </dev/null >&2
        exit $?
    fi
    echo "ArgumentError: missing keys" >&2
    exit 1
fi

if [ "$1" = '--clear' ] || [ "$1" = '-c' ]; then
    ssh-add -D > /dev/null 2>&1
    echo "All identities removed"
    exit 0
fi

if [ "$1" = '--kill' ] || [ "$1" = '-k' ]
then
    killall ssh-agent && echo "ssh-agent killed"
    exit 0
fi

if [ "$1" = '--list' ] || [ "$1" = '-l' ]; then
    ssh-add -l
    exit 0
fi

if [ "$1" = '--help' ] || [ "$1" = '-h' ]; then
cat <<EOF
keyring + 

Usage:
    keyring -e [--eval] [ARGS]
        
    keyring -a [--add] keys...
        
    keyring -c [--clear]
        
    keyring -h [--help]
        
    keyring -k [--kill]

    keyring -l [--list]

    keyring KEY:
EOF
exit 0
fi

# retrieve passphrase for key (SSH_ASKPASS style)
KEY=$( echo "$@" | sed -n 's/^.*[ \/]\([^\/].*\):\s*$/\1/p' )
if [ ! -z "$KEY" ]
then
    pass show "$PASS_KEY_PREFIX/$KEY"
else
    exit 1
fi
